[project]
authors = ["Filipe Fernandes <ocefpaf@gmail.com>"]
channels = ["conda-forge"]
description = "Cron job checking the deployed version of some ERDDAP servers out in the wild"
name = "erddap_server_versions"
platforms = ["linux-64"]
version = "1.0.0"

[tasks]
erddap_ver_check = "jupyter nbconvert --to notebook --execute erddap_server_versions.ipynb --output=erddap_server_versions-output.ipynb"

[dependencies]
python = "3.13.*"
erddapy = ">=2.2.3,<3"
nbclassic = ">=1.1.0,<2"
nbconvert = ">=7.16.4,<8"
pandas = ">=2.2.3,<3"
tabulate = ">=0.9.0,<0.10"
